# Generated by Django 4.0.4 on 2022-05-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codemodeuser',
            name='checkk',
        ),
        migrations.AlterField(
            model_name='codemodeuser',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='codemodeuser',
            name='image_url',
            field=models.URLField(blank=True, max_length=301, null=True),
        ),
        migrations.AlterField(
            model_name='codemodeuser',
            name='phone',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
