# Generated by Django 4.0.4 on 2022-05-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_codemodeuser_checkk_alter_codemodeuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codemodeuser',
            name='email',
            field=models.EmailField(default='', max_length=300),
        ),
    ]
