# Generated by Django 4.0.4 on 2022-05-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_codemodeuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='type',
        ),
        migrations.AddField(
            model_name='money',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
