# Generated by Django 4.0.4 on 2022-05-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_codemodeuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='message',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
